### ISSUE TITLE
Request: Tool parts.

### ISSUE THREAD

**Issue by Ayria** [Mrthomas20121-Mods/Blue-Skies-Tcon#1]
I saw you said you'd add tcon stuff if someone wanted them? I'm on 1.18.2 and would love to have my tinkers tools work well in blue skies worlds. Especially my hammer.

Or maybe modifiers on regular tcon tools that give blue skies mining level abilities?
If you could make either happen it would be so awesome.

**Comment by Mrthomas20121** [comment]
tldr: tools are not coming because it's not possible to make them work properly in the everdawn/everbright.
